extends: existence
message: "'%s' is jargon."
ignorecase: true
level: suggestion
tokens:
  - in the affirmative
  - in the negative
  - agendize
  - per your order
  - per your request
  - disincentivize
