extends: substitution
message: Overused Word - try one of these - '%s' instead of '%s'
ignorecase: true
level: suggestion
swap:
  'larger': 'more significant'
  'interesting' : 'exciting'
  'useful': 'helpful / valuable'
  'large': 'vast / huge / immense'
 