---

extends: default

rules:
  braces: disable
  brackets: disable
  colons: disable
  commas: disable
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines: disable
  hyphens: disable
  indentation: disable
  line-length: disable
  truthy: disable
  trailing-spaces: disable
