source "https://rubygems.org"
gem "jekyll", "~> 4.1.1"

gem 'sass-embedded', '1.63.6'

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll_picture_tag",  ">= 2.0"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# required by theme:
gem 'jekyll-include-cache'
gem "liquid-c"

gem "jekyll-inline-svg"
gem "rouge"
gem "jekyll-tagging-related_posts"
gem 'pandoc-ruby'
