---
extends: existence
message: "Start each option with a capital letter."
link: https://docs.openstack.org/contributor-guide/writing-style/lists.html
level: error
scope: list
nonword: true
tokens:
  - '^[a-z].+'
