extends: existence
message: "'%s' is a bit of a skunked term — impossible to use without issue."
ignorecase: true
level: suggestion
tokens:
  - bona fides
  - deceptively
  - decimate
  - effete
  - fulsome
  - hopefully
  - impassionate
  - Thankfully
