---
extends: spelling
message: "Did you really mean '%s'?"
level: error
code: false
ignore:
  - HouseStyle/tech-terms/general.txt
  - HouseStyle/tech-terms/mobile.txt
  - HouseStyle/tech-terms/java.txt
  - HouseStyle/tech-terms/linux.txt
  - HouseStyle/tech-terms/monitoring.txt
  - HouseStyle/tech-terms/names.txt
  - HouseStyle/tech-terms/security.txt