extends: conditional
message: "'%s' has no definition. Have you defined it?"
level: warning
scope: text
description: "Upon first mention of a new concept or software, use the full name or term, then note the abbreviation or acronym in parenthesis beside it."
link: https://www.linode.com/docs/linode-writers-formatting-guide#abbreviations-and-acronyms
first: \b([A-Z]{3,5})\b
second: (?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)
exceptions:
  - ABC
  - ADD
  - ADHD
  - AIDS
  - APA
  - API
  - CBS
  - CIA
  - CSI
  - CSS
  - CST
  - CVS
  - ESPN
  - EST
  - FAQ
  - FIXME
  - GNU
  - HIV
  - HR
  - HTML
  - HEAD
  - HTTP
  - HTTPS
  - JSON
  - LAN
  - MIT
  - MLA
  - MLB
  - MTV
  - NASA
  - NATO
  - NBA
  - NBC
  - NCAA
  - NCAAB
  - NCAAF
  - NFL
  - NHL
  - NOTE
  - PDF
  - PHP
  - PGA
  - PPV
  - PST
  - SGML
  - SSN
  - TNT
  - TODO
  - URL
  - USA
  - USSR
  - XML
  - XXX