source "https://rubygems.org"
gem "jekyll", "~> 4.1.1"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-paginate-v2", ">= 3.0"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "jekyll-inline-svg"
gem "rouge"
gem "jekyll-tagging-related_posts"