source "https://rubygems.org"
gem "jekyll", "~> 3.8.5"

gem "minima", "~> 2.0"
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-paginate-v2", ">= 3.0"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?

gem "jekyll-inline-svg"
gem "rouge"
gem "jekyll-tagging-related_posts"

