name: Build Base Image

on:
  # run build once a week
  schedule:
    - cron: '0 0 * * 0' 
  # or on demand
  workflow_dispatch:

jobs:
  build-image:
    name: Build Images
    runs-on: [earthly-satellite#gha-website]
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Site
        env:
            FORCE_COLOR: 1
            EARTHLY_INSTALL_ID: "earthly-website-githubactions"
            EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: |-
             earthly --push +build-base-images
